# Generated by Django 3.1 on 2020-08-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='title',
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.CharField(choices=[('none', 'NONE'), ('hallowner', 'hallowner'), ('mc', 'mc'), ('catering', 'catering'), ('cakers', 'cakers')], max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='user',
            table='hall_user',
        ),
        migrations.DeleteModel(
            name='Organisation',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
