# Generated by Django 3.1 on 2020-08-10 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0002_auto_20200810_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
